package com.zaita.aliyounes.gsbvc2017.network.datamodels;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


    private Integer brCode;
    private Company company;
    private String brCreationDate;
    private String brName;
    private String brTel;
    private String brAddress;
    private boolean brStatus;
    private Set branchProducts = new HashSet(0);
    private Set roleBranches = new HashSet(0);

    public Branch() {
    }

	
    public Branch(Company company, boolean brStatus) {
        this.company = company;
        this.brStatus = brStatus;
    }
    public Branch(Company company, String brName, String brTel, String brAddress, boolean brStatus, Set branchProducts, Set roleBranches) {
       this.company = company;
       this.brName = brName;
       this.brTel = brTel;
       this.brAddress = brAddress;
       this.brStatus = brStatus;
       this.branchProducts = branchProducts;
       this.roleBranches = roleBranches;
    }
   
    public Integer getBrCode() {
        return this.brCode;
    }
    
    public void setBrCode(Integer brCode) {
        this.brCode = brCode;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getBrName() {
        return this.brName;
    }
    
    public void setBrName(String brName) {
        this.brName = brName;
    }
    public String getBrTel() {
        return this.brTel;
    }
    
    public void setBrTel(String brTel) {
        this.brTel = brTel;
    }
    public String getBrAddress() {
        return this.brAddress;
    }
    
    public void setBrAddress(String brAddress) {
        this.brAddress = brAddress;
    }
    public boolean isBrStatus() {
        return this.brStatus;
    }
    
    public void setBrStatus(boolean brStatus) {
        this.brStatus = brStatus;
    }
    public Set getBranchProducts() {
        return this.branchProducts;
    }
    
    public void setBranchProducts(Set branchProducts) {
        this.branchProducts = branchProducts;
    }
    public Set getRoleBranches() {
        return this.roleBranches;
    }
    
    public void setRoleBranches(Set roleBranches) {
        this.roleBranches = roleBranches;
    }


    public String getBrCreationDate() {
        return brCreationDate;
    }

    public void setBrCreationDate(String brCreationDate) {
        this.brCreationDate = brCreationDate;
    }
}


